trigger:
  branches:
    include:
    - refs/tags/v*

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
      checkLatest: true

  - script: |
        npm install yo
        npm install 
    displayName: 'npm install'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'build'
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'test'
    
  - task: GitHubRelease@1
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      gitHubConnection: 'github.com_vikas0212git'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '$(Build.SourceBranch)'
      releaseNotesSource: 'inline'
      addChangeLog: false
